# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-26 01:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_oauthqquser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oauthqquser',
            old_name='update_tiem',
            new_name='update_time',
        ),
    ]
