# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-03 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180926_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emaiL_activate',
            field=models.BooleanField(default=False, verbose_name='邮箱验证状态'),
        ),
    ]
