# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-03 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emaiL_activate',
            new_name='emaiL_active',
        ),
    ]
