# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-03 08:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181003_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='emaiL_active',
            new_name='email_active',
        ),
    ]
